### ISSUE TITLE
In the DB there is no way to track back the ballots... so far...

### ISSUE THREAD

**Issue by krnan9525** [guilhermeleobas/e-voting#2]
yeah, no way

**Comment by guilhermeleobas** [comment]
We need to know how the irish voting system works to keep track of the ballots.

**Comment by BryanCarterDIT** [comment]
I've got that mostly sorted out into pseudo code. I need to make sure it's not going horribly wrong somehow. I think my use of "nth" is off, and it won't actually count the preferences correctly. See here for now: https://github.com/guilhermeleobas/e-voting/commit/df0788906e8d0dc57175d25abccefd05dc8205af

**Comment by guilhermeleobas** [comment]
@BryanCarterDIT this is the same as described in https://en.wikipedia.org/wiki/Single_transferable_vote
?

**Comment by BryanCarterDIT** [comment]
Yes, but it's specifically the method used here in detail, since there is an extra requirement for a niche case where a candidate can claim back the money they spent campaigning if they did not get elected but also reached a quarter of the quota.

**Comment by guilhermeleobas** [comment]
> since there is an extra requirement for a niche case where a candidate can claim back the money they spent campaigning if they did not get elected but also reached a quarter of the quota.
I don't think we need to worry about that since we're creating a tool to simulate an election.

**Comment by BryanCarterDIT** [comment]
It actually matters, since the possibility of that will force the redistribution of excess votes rather than the elimination of the bottom candidate. It's handled in the massive if (case OR case OR case) anyway.

**Comment by krnan9525** [comment]
That 'nth'  thing will not work since we are using the multithread
function. That probably may cause some synchronisation problem.

**Comment by krnan9525** [comment]
sorted!!!
